package com.example.client;

public class SoapClient {
    public static void main(String[] args) {
        /**
         * TODO: use file generated by wsimport to create instance of your service
         * CarServiceImplService serviceImpl = new CarServiceImplService();
         * CarService carService = serviceImpl.getCarServiceImplPort();
        */

        /**
         * TODO: make requests
         * carService.getCar(.....);
         * carService.rentCar(.....);
         * carService.getBackCar(.....)
         */
    }
}
